name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            vishnuindira/exercise:latest
            vishnuindira/exercise:${{ github.sha }}
            
      - name: If previous step failed, log the error
        if: ${{ failure() }}
        run: |
          echo "$(date) - Build Failure in repo: ${{ github.repository }}" >> /home/ec2-user/logs/logfile.log
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Pull the image
        run: docker pull vishnuindira/exercise:latest

      - name: Stop and remove existing container if exists
        run: docker stop my-app || true && docker rm my-app || true

      - name: Start the container
        run: docker run -d --name my-app -p 3000:8080 vishnuindira/exercise:latest

      - name: If previous step failed, log the error
        if: ${{ failure() }}
        run: |
          echo "$(date) - ${{ github.repository }}" >> /path/to/error.log
