name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Pull the image
        run: docker pull vishnuindira/exercise:latest

      - name: Stop and remove existing container if exists
        run: docker stop my-app || true && docker rm my-app || true

      - name: Start the container
        run: docker run -d --name my-app -p 3000:8080 vishnuindira/exercise:latest
